PuzzleSolver: project

project: puzzle

puzzle: Puzzle.class Tile.class SolverAlgorithm.class PuzzleToSolve.class IOReader.class IOWriter.class PuzzleSolver.class

clean:
	rm -f puzzle/*.class

Puzzle.class:
	javac puzzle/Puzzle.java

Tile.class:
	javac puzzle/Tile.java

SolverAlgorithm.class:
	javac puzzle/SolverAlgorithm.java

PuzzleToSolve.class:
	javac puzzle/PuzzleToSolve.java

IOReader.class:
	javac puzzle/IOReader.java

IOWriter.class:
	javac puzzle/IOWriter.java

PuzzleSolver.class:
	javac puzzle/PuzzleSolver.java
